language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: ISpjauz0c7OMGJTuqUgkYnfKfhnhNC013KQsFlnGygv0SxG3NqrcmPlDmNr5dl/7RD1LVHEVwJbW8QGRveeu/8DEHAZ7y4xq0troaSVrrF4kA+AFfJ+I1Ob9sFTq1lINVVfP0lK7cXIRqK/68u/kYdK0Pd0K0Q/zZ5kjTCtTsS4yK/W+dxGK7ATz7es3Y4737yQzK8NDDQs3oGcoEdPKao7be/utu6/eSAIPd+5EarY7ekVayBDZ9vpUlt57PJH0git0C5uydxRfr8rMm/05kYvAvF8gX25qe1NOtqUYn46O5i6JKnv+mLy314P9K+Tgr4ObdfGtxTDMHskHcRcy3FdjtaG3emUjRXR6CVZ/WehszDqYIr3qExfGz2acgKmLklSgzLIR2iuNXH37Q3IezcjMuKugkuprvmZxQgNJl0WWxqXx52DgepCKWksboMAByT905a8oZEMUKF/tmM2HWb3Q+D1YklRXyiqzVsMPRXtHwDB8+yCIcSMZlM58o98iga1zEmw+oxN5xfq07/3+9GdGPOwQJueRPpvmRHLGljkWWcBliwVNnSQU9Yj2Rhb3fV2Eix9I+9NiW7hfFQDkYJonuX9mWV8VJCyzuBm6OHNtAEdaFg1hDFHnsuNzPVyAsdo+YhyK4qZ8K8SKuJ3DuKR3slsU+0l3qGwL7IfUtDI=
  app: ms_usuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
