language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: JYDob1zkej50p8qNhfrqrt0JeanlY+0NQ5/2vJ/l2q+FhN+mFXJR5S6+nCleX2PGLmYbkgq5IhBAGoJiGDHbbqFpgBpjVSn4ll7xe4vY/rwHCtohb193RG1jXUaDSI/PAYeGJlo7LDix4hzNO3CNjl1ZdYOquIPhuWUt560bpODBvL8BsoZKj7SWG3E/WZExi5clFwhKnDqZkOgfElTC5sZGTrNWvCjzUXeSpKVxnh6wtHY8lPdCn6zZNmtdt61TZhsg1KAe26e2B52T00jiibynwL6HPmLwEsxouIXrqT3bVrGA1tmxURbi7SJOzU6SkEA1ySvVkvj3XQVVBXT4FE9FgKRbTQQF2+TTLCNi6sd6ol0GQgf7GUxeRB/C0wPEVbdWyo/GwH05B3aiwuHTb5zInfKZlVRP2a+f9psX6S7VwYMo4LDWvM2T1vz12XyPlwHSmR0Wk5Jqj6S0rtZfL/8TthvWftqoG9p6q9dEdGC/jwOBcJgTneU3oBSqkR5uIvPly4Rq/crsblObuttkU6esPv24ot7/XoQzL/u2kcHI8HeZsG7pLDrWd6PBMsQmP2TcP3wCTrdKZBhiwVO/qE/fkV718519+SkTvwTZHSauyyGiT/TrET15k8ZvpXIc3ORl7QeDwzKUp9OedeEnsU53Zc1vD8MCARAnOVu5bcE=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python manage.py migrate
  - restart
  skip_cleanup: 'true'
script:
- python manage.py test apps.usuarios.tests