language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: q3/NXajkAsYOaa4Hq8TOzmetfMiJfDHEOtjdRR/MeIUVLxrwmokAz/C2am3aAwuk+NAPFuiX+ojyeJE3oQ1+be9NEOskqsS3yIx9gOKWSLWozooPCyAWXq71O4pFa0fijXJBG1O1GVJV8gbhbONkRvClEXDyc5ptL6QGUvtt3pk6NmZ7BHjN9KQa/YNdPuZoy6KBGbHOpIrIV8Kk2AId3JkcbHBAFWKRlnSN/dvzqnjepEwLUDoBcDGDrNeHvyM3J8rCxksQ7tiHntt1EyKW3Tb2nRivUudAgWNgEEA1p7cfBds8Ug/4wPTj+FpCJd4Kc2Dj22yFn5IirNC3Lg3o7+VY0CNgsci4Wan4Ztbdjy7qaKPuqln0B/KP1xiJVALBIrBlZrd78z4AyDqW8Fydnzy8UwTUsmVbzkpl+kCXLiUv6pmmPgi1d26bhVfV7j5Uc5Jta1Vtp9Hi0DT6zBz1+EIXeK8A4tp0rLHmXydD0Nc9rCJuV6cEJyXdEqzGIipYc3yi9h3cq0/xLBtRD/Hs1dz92vWT07H3wywEsSVyX0ulT3iUNl5O5ykmknK01HEv2OyAcxZdG87UDQahKnCD/QpC7080sC4WpG2GBryqclFw9obuvLwHXQK9wXWt1yGYCf/vsfij5090JczIa9Y7YUcclctKR+qm4okHne/Tipg=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
