language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: FcoavRcXD9oSX++RNuE5Pamga4lsZrf8hksYZswn0LQQkQz3URdGDWRIzECerF8Us+Q1xfJKX+TyhOoJT6LEvhVQZPHVQRfMdvS+0Q7ggaaUDxPbJTDcEN9+h3c8W90u9J/SKN46ZzwNPmxD0ULjuFGYfmdYGnJcHSd7A/CjaQN/2pt661RIbKL5J/9Nsw96nc9dbalju6zSwF3HlD7CkorctXcMl+u0mWDaqKrguAjVxVec6PFhLTjOB5Mv53OqPwAx7GzCvslQ5r/xkImQrDF8lpXSuMiXBIVobNtzkooGniPzRhPp2zgqsCebDBW5dtUkOmfh9PWXd+isN70hmc9JHH4/ryc0oesYpFah9h6aEtl/d/jPfhA3c/QCZ30lFp97lJ+a8NB+vBpIXHguqBBdsJWCgjljVF3jiE6QCP7FuKpKBnJyUfJoHx9/gNtUD7PoeSD6/oGGAS1KTRfef+4s/czl5smk1poMdec1hh+VX2whW+WqeyFk1Hc0+AA+iY0POfBmF3gMjkUdw9rNsSrqP4JjLxLP70ooNSUXEdcMREaQPjWCQK22mThOYEYIVAK3MsjUFvbi/nWo59/tFdxsdWCPzNKoADBDNp5Hr1l6L1uwtmQm8MV/bi/xotluQipyCcg5rfPkcRTUxS2TRVqLHt3rD7T3a4gMWoXm6wo=
  app: ms_usuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
