language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: iBtSwntd38v9cDNRo9bKZpAjjvzIgPXStzzglgaJI/T+kJU0OjyUlmpMovb5MzjXPRSRJqyUHiW8eG8NUOOvT4/hgy7PBqqrCZN76PqZWCz87RdKDVua1B5YhG4QE4MotA8tEB1hkKgMJlSbAnYWYTFMot+pWR5ovKU2mdK6FhNUYSnRL0XKatDWJ8pxMaCGZdSJmMIBb+Vl90TLj9LEk+Bcr7/2MSgcrOayqf0tnb3uE8e58BiiEyfVBhKidmMnQYPyiU90rp821pYmzMhxW7q/xcn1TcuRuKJEJGJHMu4YjTaq+tUKPrbkZSKOMYWfzlmK9XFigThifDHDCxrJMLrr1tXYIC8N0inUTjZa5EhQz9LJtZEpjYG9mjSfP7yTBMsZnWYHDlLgcbAG++O/n9urEa/XXRqX3WCLPJTARNacC2IMtobPal1JFReHq/oGAtOyQAjJM+E+ZTgFUflkgQSEfv7zthYe1qdrOg1mVW7tl0JHZbJG6p93QwVdhlLSP7oH6joa3jitkvxNbToeKrHrDO3wSV7r2xS43Gz4MqqS4ruJu6T77scB2GpxD2mMzpw2usrvV+Ba9YG0Hv6fW9CDdIoMuQ+6/fzy2OvPfq3S0EBhE6zNni8T2Ly1Ry5HGJB6qLoxtPagHWIUGpfZZ6Ge3aVuxW1F+e5VGl4KUog=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  skip_cleanup: 'true'
script:
- python manage.py test apps.usuarios.tests
