language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: dKBc5MLlXQ4ONpZnw/2NYQS2zWZDEPYjQH0OE6EJaifjBWyQuPPmT9EcnYdL9X1CBy+Wyzc1G66nTV4mmTX0TESPV2Jlc4fP4QBIwQNCkfAR0hLm6UDwQYYBKwg3n8iaFf2lGgUe76gozc7AZtTiXWGUxJuTkilU1EdYz/CzPa36Kbl7UGOsRaUwxLtTYQjTGvoW03bqhZl+ufqL805ij3hzV/DdptNxKRvK264EQCKF6+Lhf7fT2H5IjXHAdO/Era1OvKorxGAtotuDCrHMLtn9uh20YdPwzxhN2kVJAvRPJNMtoqRiNr5Pt5JL3U3xz+JkezLtYh4xv8qO8V5nvn4nkbyG1Qhg9anOCALiDG3AwxTKXKkuxGUJzyWNr/F+4t6oqe54IDrHAnr8/LnB5Dg9hxmAPq0MQbCkpzY++XmN3G3oBSWEQyw2skWFx69P3yQZ/EyqcxO1rphA4hYeAxH/88GCLPnwKXsUZMgsP6rviknsWsC4gpIBDwdgZBZxE/PJa4I7Lczt1IELXkBs6zX8Ue/l5s3SgtWjof9cnBZuiuqS+DxuS5sxkc+k6i5n88O/ZMXXq003pvH9Dou5aFKJ5ziwtk++VDFFSMe2GopO358xP97YbT4tPL2Hzgg1U1QuY7pMdXwc2MUA+caR6qsyFKee0R8t5D6GSWLyt4w=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
