language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: MwnmBzOI4N/rLTIaisrx5v1gRUwFpd8psSVRsy9XZqZRo/p8nuCDaIx6TBsZfZUI3BFtPIkClk3N2xFtRvqKkX7JslfNK8VPxKqYZxVA25AlIdlGC9M+jd//YfdOUhzr5U05O74Yu0vxV+zQIk0uz7NcM3Z4Y4iClv+qxlJoGHRlBz/H2gErf09YXgj7HQbQglRkm5xU7RHsd5K8FU+c1t19CA3cQdqkApsQ5LF4DhlffYBupZWCuRDTmtKnpIQ0Ur7gkmgoBx56+iybwk5NFpp+RAOgHHM7A2aW7xosDdB25ED/jid3EREKURuRJPUkd6OIlbbe5xCySh5P1V5QzGZJCdJpPMxCkKhEHH6U8drLonw2S3Ua01fhIeBxWX4HhZ5HjqJTu9v8aps4mx6mfD0drX/nLf9cvP4yUsnKbFB4kMQhNnCewbDkDF9KcvBmAOMdxnhj7TbtC/N9Jbm+v6/vMWQmM6zXJNNTbvVQUe9nDlZVhlwoEmclqFFShn2voyO9NmTPS27Yr9cHo3JYZbQBfOCh0UFMzhMjQ5Ty913decAfpMHk+u5BVMrsHoglOWQob5Qt+FjUkUk2NnrTQWgOj/Zmdq1ghr9KaXwC2golUCNlyYPcasV5jLZB/lpwdXjOXtGYwW3WsgCyidr5KPs4EK8G79ukMSqmdcyzOac=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
