language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: bn6IvtpClptsYDcUDhwEmUUg07visF2DOpIWLZgY1eblmhhzwmsAgYnrXs59kq2J5KyhyXIQ6QnpAWad3Ax3FKN4sUxxlHYhD5VfydKq9qHSxHl2hoEDWHakBrq7XJLP7/nyysyCcum41loKfbXI7HfTBFZLMrc9VgclBOuCxOsr6NlDQo3Y/LGnqaKN85YrfhxB3ysSwpcQQTQKj2KsKlhkCkcXgzgGi0sK7rN2BHdXuxQcXep2vgbwzSZaXm9FeJ6zQxbdA7tDUjy2+bxhM3Vd/lM2tGMZTttvowtcOwXy2i1bJfqYdV/xrGHMaq2B443H5EcOZbl8tVB+BGA7H+JYIJ+EsT9SAyaYcblLJHXKJnP00k8N/EcavXxCBFWBx7Crxo3K4oHfiITawcspjyA9PuyoRwEiA9XdmLJ8L0zqyMIKL2PAE0C9xRWKjGOjqRgojCyJ/a2PeHn76alp5s/DDkfcAZpRIYGEDAbcv8kVqwx1m8xT7uHMWW8jyZPVN9CTEPJrkqrL4UzeOuMWLMdAWqguM/v9Nn3Qf/DIKmDc0+yNOkJZK+oruDk3zlxvtQQmvSCeSMJk9hoMExPhy+GprtrTZPK1mB+GCQuOivHbn3WuiOPDksNOYF216EwrhRRqj8ZrTzR6CRgJxCTc+FwK8lt+da7r8h7LLNDkr84=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python manage.py migrate
  - python manage.py collectstatic
  - restart
  skip_cleanup: 'true'
