language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: 26237f7a-5912-4f1f-9a36-425e351cb566
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  skip_cleanup: 'true'
script:
- python manage.py test apps.usuarios.tests
