language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
script:
- python ms_usuarios/manage.py test apps.usuarios.tests
deploy:
  provider: heroku
  api_key:
    secure: KLko53P5tYBpjqtA15yfxJxrnFZd7WI9DUdqpC2GPocElmoInLbOBOdSOHHC/a3L2OjJ+T/UmvMEVC/iHQXCwlSGnujU8as+l43HZsZ6gstUhB2xXNLlS93SoNmQ54VfSwIURWmquaA5E2zHJrDJ36HRJdRfQ7Xzz/2jQc31FG4K5IRQMKVa+b0ZMwtCEUl66NP/WJPoHZNOJwhSLbFWaTWi73mMCQ9sVyrWSrjfSK604k2r0sJNZMaSeIglNxuEwZiFtkq1coCXyDCRRgaxBm/6coLb3p0vPe5DCPcn10VrUpW5rbbPrGuYDWteJdZBre+OZZ6spVPUmZ/pFYV65cNXi52O2rCKflXq7kxbRR6siOY5oXQqNaQk2zvVdWiOlp3vEYSIiOefC221RPEbcfUUHypXihNouP2/MyvmhHpCpqB3SQdjbciDjDQuBB6JtFtx6WtXVj70zBDfMcFm4s/69zvwHacc0F1l1Cg0RM+FF0ShDX2oUhFNsTu2a3C+Y8wRgo2dYI/r9ImCEUds84sTluyEMJLP/Vgq+FanPw0sIvZVhI4OswMiQD6jd6oKJuptVwDzu/tLwif2wuyqyUwn/b3+UsSSmHLBrBWWRkb5cF8nFZaQ7omfGYFFSWumZAA80PVURBupoS3aZiyxOhL8D7n/wU/YppocIN3fvIE=
  app: ms_usuarios
  on:
    repo: ivanmviveros/ms_usuarios
  run:
  - python ms_usuarios/manage.py migrate
  - python ms_usuarios/manage.py collectstatic
  - restart
  skip_cleanup: 'true'
