language: python
before_install:
- sudo apt-get install -y libpq-dev python3-dev
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database ms_usuarios;' -U postgres
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: btm/Oai2RzHUFiwuqq3Rv/PxQohZvdlCzeVHWVpv7Aid3AeJu4pEBhJ1BU3wsebjtG4wARb/mB78u8wpMgkiHqPomLPSs3aZFxjJH5pvjihFnKsV7e8Vr0uB/yeT5AgX0CPMakd0YijObio/B7jBqCwk8pCf9xijaKoohZfl2PDmr64pZzSRsfyPs6x2dNA/n+dgHR/4XnwIz7CLpQaB7dF2L0iUMsO+NIHBRkGsEUQVzfDLslX10yvcylwVazrWLmgJlaf1r9IA9mniQ5Gq4wDxd8pMcAR5YKiH7DRXk7SyBJEyLe6STp/EJrvbvxq9XHuiorIsoqS4bbmHJYJI6kRCCKeJQkg5AMbyBGv9V1wobutPp1geyUvEalgBw16nAUTMF6BltWE4ygBWt6D+Ch1sv7KJe/CvLfr+5Q7UczzYjPs2UfFmsXw3I5lB17nL9bxLu3j/1VF4+ydngX9Xm+gUuhTbRRxrBouQOLrRbDrI2P0LiA+SIe3/qtpG6TgFmCZvz7V+STs44AcuirJsbv34kQKpWkvVb4SqDG7waOqOB+fXIZ0l3cRoBe9XcLr9MXf2rHdcvc8mYdKZ/mRTAOtRDeNAJzznfysZyBZSImtn4I+sTncY6aKKu6LhSBswGEPY4oTOYbpMOsZhUA4ayPVLi5zN5Dh8tB8h9jz3FUs=
  app: msusuarios
  on:
    repo: ivanmviveros/ms_usuarios
  skip_cleanup: 'true'
script:
- python manage.py test apps.usuarios.tests
